### PR TITLE
Fix/blackarrow arrow orientation

### LINKED ISSUE #226: Fix blackarrow arrow orientation
See branch `fix/blackarrow-arrow-orientation`. I updated **blackArrow** story to illustrate the problem.

image

### PR DESCRIPTION
**Pull request by nicoespeon**
Fixes #226

Result:

image

### CODE REVIEW

File: packages/gitgraph-core/src/utils.ts [hunk 1]
```diff
@@ -193,26 +194,24 @@ function getAlpha<TNode = SVGElement>(
       break;
   }
 
+  // If commit is distant from its parent, there should be no angle.
```
Comment (nicoespeon) [inline packages/gitgraph-core/src/utils.ts]: At first, I thought this applied only to reverse arrow scenarios. But it turns out I was wrong. Now it works for every scenario.

Comment (nicoespeon) [reply packages/gitgraph-core/src/utils.ts]: cc @fabien0102 ;-)
